server:
  port: 8298
springdoc:
  swagger-ui:
    enabled: true
    path: /tradingsignals/swagger.html
  api-docs:
    path: /tradingsignals/docs
spring:
  application:
    name: crypto-trading-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/tradingsignal
  flyway:
    url: jdbc:postgresql://localhost:5432/tradingsignal
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password


