server:
  port: 8298
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /apidocs/
spring:
  application:
    name: crypto-trading-signal
  datasource:
    username: user
    password: password
    url:  jdbc:postgresql://localhost:5432/tradingsignal
  flyway:
    url: jdbc:postgresql://localhost:5432/tradingsignal
    user: user
    password: password


