server:
  port: 8298
springdoc:
  swagger-ui:
    enabled: true
    path: /tradingsignals/swagger.html
  api-docs:
    path: /tradingsignals/docs
spring:
  application:
    name: crypto-trading-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/tradingsignal
  flyway:
    url: jdbc:postgresql://localhost:5432/tradingsignal
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

sma:
  shortPeriod: 9
  longPeriod: 21
ema:
  shortPeriod: 12
  longPeriod: 26
rsi:
  period: 14
bbands:
  period: 20
  stddev: 2
macd:
  fastPeriod: 12
  slowPeriod: 26
  signalPeriod: 9
obv:
  maperiod: 14
stoch:
  fastKPerdiod: 14
  slowKPerdiod: 3
  slowDPerdiod: 3

crypto-data:
  apiEndpoint: https://api.binance.com
