server:
  port: 8298
springdoc:
  swagger-ui:
    enabled: true
    path: /tradingsignals/swagger.html
  api-docs:
    path: /tradingsignals/docs
spring:
  application:
    name: crypto-trading-signal
  r2dbc:
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    url:  r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tradingsignal}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tradingsignal}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:user}
    password: ${RABBIT_PASSWORD:password}


