server:
  port: 8288

spring:
  application:
    name: crypto-trading-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/tradingsignal
  flyway:
    url: jdbc:postgresql://localhost:5432/tradingsignal
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

sma:
  shortPeriod: 9
  longPeriod: 21
rsi:
  period: 14
bbands:
  period: 20
  stddev: 2
macd:
  fastPeriod: 12
  slowPeriod: 26
  signalPeriod: 9

crypto-data:
  apiEndpoint: https://api.binance.com
