spring:
  application:
    name: crypto-trading-signal
  sql:
    init:
      mode: always
    datasource:
      username: user
      password: password
      url: jdbc:postgresql://localhost:5432/tradingsignal
      driverClassName: org.postgresql.Driver
sma:
  shortPeriod: 9
  longPeriod: 21

crypto-data:
  apiEndpoint: https://api.binance.com
  symbols:
    - MANAUSDT
    - BATUSDT
    - CHZUSDT
    - COMPUSDT
    - SANDUSDT
    - ADAUSDT
    - XLMUSDT
    - AUDIOUSDT
    - ZRXUSDT
    - XRPUSDT
    - AVAXUSDT
    - LINKUSDT
    - LTCUSDT
    - AAVEUSDT
    - SLPUSDT
    - DOTUSDT
    - MKRUSDT
    - AXSUSDT
    - FETUSDT
    - BCHUSDT
    - GRTUSDT
    - SKLUSDT
    - FTMUSDT
    - HBARUSDT
    - MATICUSDT
    - SOLUSDT
    - BTCUSDT
