server:
  port: 8288

spring:
  application:
    name: crypto-trading-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/tradingsignal
  flyway:
    url: jdbc:postgresql://localhost:5432/tradingsignal
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

sma:
  shortPeriod: 9
  longPeriod: 21

crypto-data:
  apiEndpoint: https://api.binance.com
  symbols:
    - MANAUSDT
    - BATUSDT
    - CHZUSDT
    - COMPUSDT
    - SANDUSDT
    - ADAUSDT
    - XLMUSDT
    - AUDIOUSDT
    - ZRXUSDT
    - XRPUSDT
    - AVAXUSDT
    - LINKUSDT
    - LTCUSDT
    - AAVEUSDT
    - SLPUSDT
    - DOTUSDT
    - MKRUSDT
    - AXSUSDT
    - FETUSDT
    - BCHUSDT
    - GRTUSDT
    - SKLUSDT
    - FTMUSDT
    - HBARUSDT
    - MATICUSDT
    - SOLUSDT
    - BTCUSDT