name: Build and run unit-tests
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: leandrodalbo/tradingsignalsapi
  VERSION: ${GITHUB_SHA}


jobs:
  useVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo ${{ env.VERSION }}
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Vulnerabilities Scan
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload Vulnerabilities report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build + UnitTests
        run: |
          chmod +x gradlew 
          ./gradlew build